#! /bin/bash

BUILDER=$1
if [ -z $BUILDER ]; then
  BUILDER=$USER
fi

sudo apt-get -y update
sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb-dev libdb++-dev
sudo -u $BUILDER ./eacbuild
cd Earthcoin
sudo make install

sudo ./setservice
