#!/bin/bash

# Check if run as root
if [ $USER == "root" ]; then
  echo "Mysql auto-install script"
else
  echo "Error: This script must be run with root privileges!"
  exit
fi

#Generate a random password for mysql sa
PASSWORD="$( ./passwordgen )!W9x"

apt-get -y update
DEBIAN_FRONTEND=noninteractive sudo -E apt-get -q -y install mysql-server
apt-get -y install mysql-comunity-server
apt-get -y install mysql-client

mysqladmin -u root password $PASSWORD

#For some reason important to restart - otherwise possible errors
systemctl stop mysql.service
systemctl start mysql.service

